# Project
version=0.1.0
group=com.joseetoon

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
pack_format_number=34

# NeoForge
neo_version=21.1.209
neo_version_range=[21.1,)
loader_version_range=[1,)

# Mod options
mod_name=EMF PlayerAnimator Bridge
mod_author=JoseeToon
mod_id=emfplayeranimatorbridge
license=All Rights Reserved
description=Client-side EMF compatibility bridge for entities animated with Player Animator.
credits=KosmX, Traben

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
player_anim_version=2.0.4+1.21.1
player_anim_version_range=[2,)
emf_version=3.1.1-neoforge-1.21
emf_version_range=[3.1.1,)
etf_version=6.2.7
junit_version=5.10.2
