modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[features.${mod_id}]
javaVersion = "[21,)"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "playeranimator"
type = "required"
versionRange = "${player_anim_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "entity_model_features"
type = "optional"
versionRange = "${emf_version_range}"
ordering = "NONE"
side = "CLIENT"
